name: branch 관리

on:
  pull_request_target:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR branch
        run: |
          base_branch=$(jq -r '.pull_request.base.ref' "$GITHUB_EVENT_PATH")
          head_branch=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")

          if [ "$base_branch" == "main" ]; then
            if [ "$head_branch" != "dev" ]; then
              echo "PRs to main branch are only allowed from the dev branch."
              exit 1
            fi
          fi
